name: infra-platform

services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    restart: unless-stopped
    ports:
      - "7072:7071"
    volumes:
      - ./config-repo:/config-repo
    environment:
      SPRING_PROFILES_ACTIVE: native
      CONFIG_REPO_LOCATION: file:/config-repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - ms-net

  registry-server:
    build:
      context: ./registry-server
      dockerfile: Dockerfile
    container_name: registry-server
    restart: unless-stopped
    ports:
      - "7082:7081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CONFIG_SERVER_URL: http://config-server:7071
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - ms-net

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - "7092:7091"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CONFIG_SERVER_URL: http://config-server:7071
    depends_on:
      config-server:
        condition: service_healthy
      registry-server:
        condition: service_started
    networks:
      - ms-net

networks:
  ms-net:
    name: ms-net
